// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcuxiy5Y_z1KrdoNT4yoYNC4B7T3vnKvc',
    appId: '1:745378410233:web:0b6ae379ad06a2f56dfc28',
    messagingSenderId: '745378410233',
    projectId: 'staying-consistent-6d22a',
    authDomain: 'staying-consistent-6d22a.firebaseapp.com',
    storageBucket: 'staying-consistent-6d22a.firebasestorage.app',
    measurementId: 'G-SGVCSGYRMQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTWyRQ-D9h3t5Nq0HJ1EoCC2AuC31SrU8',
    appId: '1:745378410233:android:e943e76be218a65e6dfc28',
    messagingSenderId: '745378410233',
    projectId: 'staying-consistent-6d22a',
    storageBucket: 'staying-consistent-6d22a.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqV9FYd4b_21YtVNjLtJEz3P4r5hn2kGo',
    appId: '1:745378410233:ios:648cefed220eea306dfc28',
    messagingSenderId: '745378410233',
    projectId: 'staying-consistent-6d22a',
    storageBucket: 'staying-consistent-6d22a.firebasestorage.app',
    iosBundleId: 'com.example.consistentTrackerApp',
  );
}
